### ISSUE TITLE
Fix your shit.

### ISSUE THREAD

**Issue by GoddofCarrots** [StefanLobbenmeier/youtube-dl-gui#122]
Why do I have to cancel ALL the processes separately in Task Manager? Why do you force me to add 200 videos back to my queue after restarting the dozenth time because you grey out the delete button until they're added?
It's a fucking mess and I spent over half my time messing around rather than just being able to download videos.

At least it's free? Except the unreasonable amount of time I spent. Thanks.

**Comment by StefanLobbenmeier** [comment]
(Close for rudeness)

**Comment by Lol12332okay** [comment]
Bro wtf
