### ISSUE TITLE
Downloads don't work on X videos

### ISSUE THREAD

**Issue by Akhlys** [StefanLobbenmeier/youtube-dl-gui#123]
Since fairly recently, twitter.com forwards to x.com.
None of the videos on X seem to be able to be downloaded.
The error report seems fairly generic, suggesting it doesn't know what to do with X, but manually changing the url to twitter doesn't work either.
I suppose a simple "if url.domain == x go to twitter" would suffice, I doubt they changed too much

To reproduce:
1. Visit [this sample vid on X](https://x.com/Catsillyness/status/1793977175449981128) to find a nice cat video
2. copy that url into open video downloader
3. Add it to the DL list
4. Get greeted by an "Error! Unhandled error (execa)"

Log:
```
{
  "shortMessage": "Command failed with exit code 1: C:\\Users\\noneofyourbuisness\\yt-dlp.exe -J --flat-playlist --file-access-retries 3 --no-cache-dir --ignore-config --user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 --no-check-certificate --cookies C:\\cookies.txt --yes-playlist https://x.com/Catsillyness/status/1793977175449981128",
  "command": "C:\\Users\\noneofyourbuisness\\yt-dlp.exe -J --flat-playlist --file-access-retries 3 --no-cache-dir --ignore-config --user-agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 --no-check-certificate --cookies C:\\cookies.txt --yes-playlist https://x.com/Catsillyness/status/1793977175449981128",
  "escapedCommand": "\"C:\\Users\\noneofyourbuisness\\yt-dlp.exe\" -J --flat-playlist --file-access-retries 3 --no-cache-dir --ignore-config --user-agent \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36\" --no-check-certificate --cookies \"C:\\cookies.txt\" --yes-playlist \"https://x.com/Catsillyness/status/1793977175449981128\"",
  "exitCode": 1,
  "stdout": "null",
  "stderr": "WARNING: [generic] Falling back on generic information extractor\nERROR: Unsupported URL: https://x.com/Catsillyness/status/1793977175449981128",
  "failed": true,
  "timedOut": false,
  "isCanceled": false,
  "killed": false
}
```

**Comment by StefanLobbenmeier** [comment]
This is fixed in the yt-dlp nightly:

https://github.com/yt-dlp/yt-dlp/issues/9923#issuecomment-2120222496

you can wait for the ~monthly release, fix this manually by updating to nightly yourself like in the linked comment, or you can try v3 which currently always downloads yt-dlp nightly https://github.com/StefanLobbenmeier/yt-dlp-compose/releases

**Comment by Akhlys** [comment]
Thanks
updating it to nightly worked.

**Comment by StefanLobbenmeier** [comment]
With the new release of yt-dlp https://github.com/yt-dlp/yt-dlp/releases/tag/2024.05.26 this should also now work automatically as long as update binaries automatically is turned on
