### ISSUE TITLE
Option to create subdirectories based on YouTube username and/or playlist name

### ISSUE THREAD

**Issue by dizzy-egg** [StefanLobbenmeier/youtube-dl-gui#15]
**Is your feature request related to a problem? Please describe.**
Would be great if videos could be downloaded to separate subdirectories based on the YouTube channel name and/or playlist names. 

Such an option exists in 4K Video Downloader.

**Comment by StefanLobbenmeier** [comment]
Somewhat duplicates https://github.com/StefanLobbenmeier/youtube-dl-gui/issues/9

But actually partially this is already implemented. You can configure the target file in the app settings:

![image](https://user-images.githubusercontent.com/36509607/211172410-1c8d94af-6c2a-4d58-85d4-e16883f65d5a.png)


There you can use output templates like here: https://github.com/yt-dlp/yt-dlp#output-template

Unfortunately there is a bug (#9) that we cannot use playlist information here. But youtube channel name should be no issue, For example this format  `%(uploader)s/%(title).200s-(%(height)sp%(fps).0d).%(ext)s` will place this video https://www.youtube.com/watch?v=eEBnckCJJ_U into "C:\Users\Stefan\Downloads\NCS Arcade\Tatsunoshin - Light Me Up (feat. Giin) [Arcade Release]-(480p30).mp4"
