### ISSUE TITLE
File Thumbnail Breaking

### ISSUE THREAD

**Issue by GreatWaldo** [StefanLobbenmeier/youtube-dl-gui#150]
Hello, I was using Open Video Downloader normally until November 4th. A downloaded video file did not display normally. In a video player app, it will flicker multiple times before playing like normal. This does not happen to every video downloaded but has become more frequent than when this first appeared. 

I have no idea what causes this beyond assuming those breaking dependencies mentioned in the v3 announcement. The only user end fix I suspect might come from one video that failed to download from an error which said to "dump the cache" yet I have no clue what cache to dump, as the open-video-downloader folder lacks any .cache files. Until v3 comes out a month from now, can this bug be hotfixed?

![OVD Broken File Thumbnail Sample](https://github.com/user-attachments/assets/24d20982-9ad9-4f3d-ba60-b8c56002f983)
[Bottom left]

**Comment by StefanLobbenmeier** [comment]
Unfortunately I have no idea what could be causing this, possibly this is an issue in yt-dlp or ffmpeg

**Comment by GreatWaldo** [comment]
Thank you for explaining the problem. yt-dlp updated on November 4th so something might have broken with it.
