### ISSUE TITLE
Add option to add thumbnail to video

### ISSUE THREAD

**Issue by TheInsane101** [StefanLobbenmeier/youtube-dl-gui#152]
**Is your feature request related to a problem? Please describe.**
This might be my favourite GUI for YT-DLP, as it downloads all the video's metadata I need, as well as the subtitles and chapters, but I can't find any option to have the thumbnail merged into the final video file. I only see the option to download the thumbnail as a separate file, but I don't need that option.

**Describe the solution you'd like**
It would be great to have the option to merge the thumbnail into the downloaded video and not just have it separate. This should even be default.

**Describe alternatives you've considered**
Other GUIs don't download the video metadata I care about, like the Youtuber and the URL. Tartube is the only one that does, but it's too advanced for me and adds a whole bunch of folders for their feature of grouping downloads from within the app, but I don't need that. I just want to download individual videos into my own folders and play them from within Explorer, not the downloader app. This Open Video Downloader is the closest to my dream downloader; the thumbnail issue is the only problem it has.

**Additional context**

**Comment by StefanLobbenmeier** [comment]
The option you are looking for is embed thumbnail and it’s implemented in v3

**Comment by TheInsane101** [comment]
Oh ok thx

**Comment by StefanLobbenmeier** [comment]
Yeah you can give it a try over here:
https://github.com/StefanLobbenmeier/yt-dlp-compose

I will merge it to this repo once it has feature parity (or at least very close) to v2
