### ISSUE TITLE
Error in main process

### ISSUE THREAD

**Issue by Gizmodo** [StefanLobbenmeier/youtube-dl-gui#156]
**Describe the bug**
Ive try to download two videos from YouTube and get an error

**Screenshots**
![image](https://github.com/user-attachments/assets/052c53ad-3325-4344-a7f6-404c380ec6f0)

**Additional info (please complete the following information):**
 - OS: Win11
 - Application version 2.5.4
 - Application type installer

**Comment by StefanLobbenmeier** [comment]
this is very curious - apparently instead of getting proper json from yt-dlp we just got 4

I can reproduce the javascript error with this code:

```javascript
var liveDataObj = JSON.parse("4")
"fragment_count" in liveDataObj
```

which is what must have happened in this piece of code:

https://github.com/StefanLobbenmeier/youtube-dl-gui/blob/3f423bfbb9133dc834dce8cb67228b2fc9afe673/modules/download/DownloadQuery.js#L186-L194

Can you share the video urls so I can attempt to reproduce?

**Comment by Gizmodo** [comment]
https://www.youtube.com/watch?v=mNKQ9dc1knI
https://www.youtube.com/watch?v=UNOkvk_fMmM
https://www.youtube.com/watch?v=ueYSn3THUIA
https://www.youtube.com/watch?v=wg4FWfBNVgk

**Comment by StefanLobbenmeier** [comment]
Could not reproduce this unfortunately. But glad to see another jetpack compose enjoyer (v3 is developed with jetpack compose desktop) 😄

**Comment by Gizmodo** [comment]
Let's close this issue as I could not repoduce error too. Switch to yt-dlp-compose

**Comment by Gizmodo** [comment]
I catch error again. I add only one video to download list. Select 1080p. After oress OK, video downloading continued. It happend between 75 and 90 percent. [Url ](https://www.youtube.com/watch?v=0OSJ_PtCPgg&t=117s) I try again and no more error. How to turn on logging, maybe it helps?

**Comment by vengin** [comment]
Started having the same problem all of a sudden. For the same URL it occurs when downloading Video+Audio, but does not occur when downloading Audio only. What's even stranger, is that there was no error before (even though haven't updated either Open Video Downloader, or yt-dlp or ffmpeg).
BTW, the old 2.4.0 installation version does not give this error...
