### ISSUE TITLE
ReadMe link redirects to Jely2002 release, not StefanLobbenmeier Release

### ISSUE THREAD

**Issue by MintMain21** [StefanLobbenmeier/youtube-dl-gui#17]
**Describe the bug**
The description on GitHub for this fork is essentially copy/pasted from the original build by Jely2002. Unfortunately, this means the "how to install" link redirects to the older release as well, instead of the latest release of the fork.

**To Reproduce**
1. Go to description/readme
2. Click on 'Download the [applicable installer or executable](https://github.com/jely2002/youtube-dl-gui/releases/latest) for your system.'
3. See error

**Expected behavior**
The link should be for the latest release of the StefanLobbenmeier fork. (https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/latest)

**Additional context**
It's only a single link that needs to be edited, as demonstrated by this very report.

**Comment by StefanLobbenmeier** [comment]
Good idea, I should also fix the other urls to link to this repository

**Comment by venkat2305** [comment]
The credit in the app also redirects to the old build. It should open this repo.
