### ISSUE TITLE
Audio download greater than 100%

### ISSUE THREAD

**Issue by chipsenkbeil** [StefanLobbenmeier/youtube-dl-gui#21]
**Describe the bug**
Percentage of download is greater than 100% for some audio.

**To Reproduce**
1. Download videos for https://www.youtube.com/@Mony514 ([video from screenshot](https://www.youtube.com/watch?v=YxFlyDT_JQ4))
2. Examine audio output percentage for some of them is greater than 100%

**Expected behavior**
Does not exceed 100%.

**Screenshots**

<img width="623" alt="image" src="https://user-images.githubusercontent.com/2481802/213306273-9d5bf46a-9cc4-4aec-9ecc-85d9c0533219.png">

**Additional info (please complete the following information):**
 - OS: Mac 13.1 
 - Application version: 2.4.8
 - Application type: app from dmg

**Additional context**
I enabled subtitles for all of the videos, if that possibly impacts the percentage.

**Comment by StefanLobbenmeier** [comment]
I Wonder if this is some weird effect from https://github.com/StefanLobbenmeier/youtube-dl-gui/pull/12

anyway, I will take a look at the logs from the download, we get the progress % directly from yt-dlp, so if it gives us a higher percentage there then we display it

**Comment by StefanLobbenmeier** [comment]
Just gave it 2 tries with your video, once without subtitles and then with.

Did not notice the percentage going above 100%, also not in the logs:

```
[download] 100.0% 2.55MiB/s  {"downloaded_bytes": 22916700, "total_bytes": 22916700, "filename": "C:\\Users\\Stefan\\Downloads\\Mony Mony\\Master Keaton Episode 35-(240p24).f140.m4a", "status": "finished", "elapsed": 8.558793067932129, "ctx_id": null, "speed": 2677562.106959183, "_speed_str": "2.55MiB/s", "_total_bytes_str": "  21.86MiB", "_elapsed_str": "00:00:08", "_percent_str": "100.0%", "_default_template": "100% of   21.86MiB in 00:00:08 at 2.55MiB/s"}                                                                                                                                                                                                                                            
[Merger] Merging formats into "C:\Users\Stefan\Downloads\Mony Mony\Master Keaton Episode 35-(240p24).mkv"
[EmbedSubtitle] Embedding subtitles in "C:\Users\Stefan\Downloads\Mony Mony\Master Keaton Episode 35-(240p24).mkv"
Download finished
```

So it seems to work as excepted now. The App only parses the output from the logs, so it might be that yt-dlp sometimes prints a higher number for some reason. If you can reproduce it again, please include the logs from the download
