### ISSUE TITLE
[Open File] and [Show file in folder] not working.

### ISSUE THREAD

**Issue by oGrqpez** [StefanLobbenmeier/youtube-dl-gui#25]
**Describe the bug**
[Open File] and [Show file in folder] do not work, when clicking [Show file in folder], it gives an error stating it couldn't find the file that ended with .webm.

**To Reproduce**
1. Get a video link
2. Download it
3. Wait until it's done
4. Click either button, nothing will work

**Expected behavior**
When clicking "open file", it should open in vlc, and "show in folder" should show the folder it is located in

**Screenshots**
![YaRl7fpYqD](https://user-images.githubusercontent.com/76074246/216603094-c073a909-b260-4727-8177-aa3a31631824.png)

**Additional info (please complete the following information):**
 - OS: Windows 10 Pro
 - Application version 2.4.8
 - Application type: Portable
 
 The file is an mp4

**Comment by StefanLobbenmeier** [comment]
Duplicates #7 

sorry did not get to fix that yet
