### ISSUE TITLE
Unable to download video from YouTube

### ISSUE THREAD

**Issue by Gizmodo** [StefanLobbenmeier/youtube-dl-gui#29]
**Describe the bug**

**To Reproduce**
1. Add link https://www.youtube.com/watch?v=kCIvmQYgFbQ
2. Got error: "Unable to extract uploader id"

**Additional info (please complete the following information):**
 - OS: Windows 11
 - Application version: 2.4.8
 - Application type: Open-Video-Downloader-Setup-2.4.8

**Screenshots**
![image](https://user-images.githubusercontent.com/1078610/219659182-e0911cba-efe2-4ebd-98f5-98f008337128.png)

**Comment by StefanLobbenmeier** [comment]
Hmm the link you provided works locally for me. Could you check if there is an update to yt-dlp as the message suggests? Maybe you have this setting turned off?
![Image 17 02 23 at 19 28](https://user-images.githubusercontent.com/36509607/219751744-fdf7deab-9077-458b-8cda-3df6a68099aa.jpeg)

**Comment by StefanLobbenmeier** [comment]
Also your bug report came in 6 minutes after a new release of yt-dlp, I wonder if starting open video downloader while yt-dlp is releasing can break something.

**Comment by Gizmodo** [comment]
I've got ytdlp 2023.02.17
Auto-update ytdl binary and auto-update app are on.
![image](https://user-images.githubusercontent.com/1078610/219868671-4b249a79-7997-45e7-8545-34f89629cb05.png)

**Comment by Gizmodo** [comment]
I try to add -vU params and downloading works
![image](https://user-images.githubusercontent.com/1078610/219868824-c17aca57-5a02-45c6-9786-9dbedabaedc7.png)

**Comment by StefanLobbenmeier** [comment]
Hmm strange that it was somehow stuck on the old version. Glad you were able to resolve it yourself :)
