### ISSUE TITLE
Limited speed?

### ISSUE THREAD

**Issue by cferron** [StefanLobbenmeier/youtube-dl-gui#32]
When downloading Youtube audi or video, the speed is very slow. I have not set any limitations in the preferences.

 - OSX 13.2.1
 - Application version 2.4.8
 - Application type installer from GIT Hub

Thanks

**Comment by Borisov707** [comment]
Same issue

Tried to connect via VPN to different locations. result the same

WIndows 10 22H2
Application version 2.4.8
Application type installer from GIT Hub

**Comment by StefanLobbenmeier** [comment]
There is little i can do to help you there. If you want, give me the video urls and I can measure the speed on my machine, but most likely the speed limit is by YouTube. 

If you can reproduce with the yt-dlp cli then we can raise an issue there, maybe there is a regression on their end.

**Comment by StefanLobbenmeier** [comment]
They are already aware: https://github.com/yt-dlp/yt-dlp/issues/6369

When they release it you should get the update.

**Comment by StefanLobbenmeier** [comment]
Will leave it open until the release to avoid others reporting the same issue, but it seems it will be released soon

**Comment by StefanLobbenmeier** [comment]
Fix was just released, all you have to do is restart and it should download it https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.03
