### ISSUE TITLE
[Feature request] Skip download if its been downloaded before and still exists in output dir

### ISSUE THREAD

**Issue by DjordjeMandic** [StefanLobbenmeier/youtube-dl-gui#35]
**Is your feature request related to a problem? Please describe.**
Starting same download will result in complete redownload and rewrite of already downloaded file.

**Describe the solution you'd like**
 * Add option to skip download of playlist entry if it already exists in output directory (same file name and extension) before starting playlist download.

 * Add popup notifying user that specific file already exists and that it will be overwritten when downloading only one video.(popup should have option to cancel the operation).

**Comment by StefanLobbenmeier** [comment]
Hmm usually those videos should already be skipped. See also #22
