### ISSUE TITLE
Which is the original installation file?

### ISSUE THREAD

**Issue by ghost** [StefanLobbenmeier/youtube-dl-gui#39]
**Is your question related to a problem? Please describe.**

**Describe the question you have.**
What is the difference between these two files and which one should I choose for Windows?

**Additional context**
<details>
 <summary>screenshot</summary>

![resim](https://user-images.githubusercontent.com/110184059/223635169-2b03bf09-297b-4908-9e73-50938d632b1b.png)

</details>

**Comment by StefanLobbenmeier** [comment]
I am not 100% sure, but I would guess one of them is a setup that you install, while the other is a portable edition.
