### ISSUE TITLE
Use ytdlp

### ISSUE THREAD

**Issue by bob27aggiustatutto** [StefanLobbenmeier/youtube-dl-gui#41]
Use https://github.com/yt-dlp/yt-dlp over "classic" ytdl

**Comment by StefanLobbenmeier** [comment]
Good idea, that’s why we’re already doing that since 2.4.0 😄 

I guess the title of the project could change eventually to reflect it, but for now I prefer the old title.

**Comment by bob27aggiustatutto** [comment]
I was mislead by the title then. Sorry.

**Comment by StefanLobbenmeier** [comment]
All good, thanks for the idea
