### ISSUE TITLE
ffmpeg not found.

### ISSUE THREAD

**Issue by rrondo** [StefanLobbenmeier/youtube-dl-gui#45]
Hey! Could you help me to fix that? Some videos download fine, but the rest have this strange error:

![Open_Video_Downloader_cstXGjvfTo](https://user-images.githubusercontent.com/46533574/231357015-4ac2e7e2-b9e1-4110-9195-fc29f75bb75e.jpg)

 - OS: Windows 10
 - Application version 2.4.8
 - Application type installed version

Thanks!

**Comment by StefanLobbenmeier** [comment]
It should download FFmpeg on its own after you start the application. You could try restarting the application to give it a chance to do that again.

But it might be that something changed that broke the download on the server side, I noticed on the original repo there are also 2 fresh bug reports: 
https://github.com/jely2002/youtube-dl-gui/issues/486
https://github.com/jely2002/youtube-dl-gui/issues/487

**Comment by StefanLobbenmeier** [comment]
It looks like somehow the ffmpeg release page has an outdated certificate
![image](https://user-images.githubusercontent.com/36509607/231455558-edde2424-8bf6-4ed0-ad7a-541c2c08dd2b.png)

I will have to ask them to renew it

**Comment by StefanLobbenmeier** [comment]
Hmm no its certainly related, but actually their certificate is up to date when I open https://ffbinaries.com/api/v1/version/latest in the browser: 

![image](https://user-images.githubusercontent.com/36509607/231455867-4b6be124-2200-45ca-80d4-53c5faa9d39a.png)

**Comment by rrondo** [comment]
Thank you, Stefan! That worked for me, problem solved.

**Comment by ENTPRESTIGIOUS** [comment]
I have this error having updated to 2.4.9

**Comment by StefanLobbenmeier** [comment]
You’re right, on MacOS the workaround is required after the update, other platforms should be fine.

**Comment by StefanLobbenmeier** [comment]
@ENTPRESTIGIOUS just did a hotfix in 2.4.10, can you try again?

**Comment by StefanLobbenmeier** [comment]
https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.4.10

**Comment by victokurk** [comment]
@StefanLobbenmeier Thank you. Updating from 2.4.8 to 2.4.10 fixed this error for me.

**Comment by philoupd** [comment]
I have 2.5.4 installed on my MacBook Pro M3 pro and still have this issue also after replacing ffmpeg and ffprobe as described above. Am I missing something or am I doing something it wrong?

**Comment by StefanLobbenmeier** [comment]
@philoupd one thing that might cause this is that it currently downloads the x64 ffmpeg, so it requires Rosetta to be installed.
