### ISSUE TITLE
Graphical Bug

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [StefanLobbenmeier/youtube-dl-gui#50]
It appears that the drag icon to re-arrange the downloads is overlapping the bottom part of the menu as if the z-index was higher than the menu?
![image](https://user-images.githubusercontent.com/45579671/233268025-720b6418-90cf-4ff3-826f-de01b971e1e5.png)

**Comment by ENTPRESTIGIOUS** [comment]
![image](https://user-images.githubusercontent.com/45579671/233268219-bb9ca119-f02b-4206-b8dc-f79964873652.png)

**Comment by ngoclong19** [comment]
I can confirm this issue:
![ảnh](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/2577653/62f21c6a-7647-4a57-b0df-8e57dedcc3a9)

Also, for this video, the UI looks strange:
`https://www.twitch.tv/videos/1843958486`
![ảnh](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/2577653/c3a8a5a2-b9b0-4b6b-bd6b-910604ddbbef)
