### ISSUE TITLE
Error reported! Report ID: cf4c22c2

### ISSUE THREAD

**Issue by L0rn1996** [StefanLobbenmeier/youtube-dl-gui#62]
![Error](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/131600189/42072fb8-795f-4ff2-b987-6d36ca789157)

**Comment by StefanLobbenmeier** [comment]
What exactly are you asking for? 

The url you are using is not supported by yt-dlp, if you want support for it you can create an extractor for it. 

If it is your site you can also check if it is easier to make the site compatible with the generic extractor

**Comment by L0rn1996** [comment]
Well, i guess thats the reason. You can delete this issue.
