### ISSUE TITLE
Twitter no longer working, is it due to new login requirements?

### ISSUE THREAD

**Issue by rugabunda** [StefanLobbenmeier/youtube-dl-gui#63]
If so, can we add twitter cookie support to video downloader?

**Comment by StefanLobbenmeier** [comment]
Could be. There is already basic cookie support (it can be improved though)

basically follow this guide, but replace YouTube with Twitter https://github.com/StefanLobbenmeier/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists

**Comment by rugabunda** [comment]
> Could be. There is already basic cookie support (it can be improved though)
> 
> basically follow this guide, but replace YouTube with Twitter https://github.com/StefanLobbenmeier/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists

Thank you so much! Will take a look!

**Comment by rugabunda** [comment]
Oh does this override my youtube cookie I am currently using?

**Comment by rugabunda** [comment]
> Could be. There is already basic cookie support (it can be improved though)
> 
> basically follow this guide, but replace YouTube with Twitter https://github.com/StefanLobbenmeier/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists

Oh does this override my youtube cookie I am currently using or can they be combined in the same text file?

**Comment by StefanLobbenmeier** [comment]
I think putting them both in one text file would work
