### ISSUE TITLE
Missing non-Latin characters in Download Log window

### ISSUE THREAD

**Issue by artquest** [StefanLobbenmeier/youtube-dl-gui#64]
When I download videos with non-Latin names and discriptions (Russian in my case), these names are displayed with question mark symbols (screen attached) in Download Log window. Yet it's ok in the main and info windows (screen attached).
Plus I have this strange animation when I open any already downloaded video's Download Log for the second and subsequent times (gif attached).

I'm on Windows 10 x64. OVD 2.4.10.

![Snap6](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/24230703/361e951a-b873-4a8e-ab9c-a4306ba9b35d)

![Snap8](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/24230703/c5c18a75-e293-498a-9bac-0bde9336551b)

![record_107](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/24230703/98c7229b-4244-4c23-96c0-2a224acaaa58)

**Comment by StefanLobbenmeier** [comment]
Woah that bug is a nice find. I am guessing this is that the videos are somehow setting the text value there in a loop and somehow there are now 2 loops setting that value. Habe mot touched that part of the code yet
