### ISSUE TITLE
any video add to queue will clear and wait long time to show

### ISSUE THREAD

**Issue by foreversos** [StefanLobbenmeier/youtube-dl-gui#68]
can not show down info immediately

**Comment by foreversos** [comment]
after downling metadata

**Comment by StefanLobbenmeier** [comment]
I think what you are trying to describe, is that when videos are added they appear briefly, then disappear and when metadata is loaded they appear again. I also noticed that behavior.

Not much we can do here, the new version has a much better architecture regarding that and will fix it

**Comment by foreversos** [comment]
OK.hope it OK
