### ISSUE TITLE
On Kubuntu 22.04.3, Open-Video-Downloader-2.5.2.AppImage does not run.

### ISSUE THREAD

**Issue by SnowballV** [StefanLobbenmeier/youtube-dl-gui#74]
**Describe the bug**
On Kubuntu 22.04.3, Open-Video-Downloader-2.5.2.AppImage does not run.

**To Reproduce**
1. Download and save Open-Video-Downloader-2.5.2.AppImage;
2. Double click the saved Open-Video-Downloader-2.5.2.AppImage;
3. 'What do you wish to do with this file?' Choose 'Execute';
4. Confirm to start the program Open-Video-Downloader-2.5.2.AppImage, by selecting 'Continue' (thus setting it as executable);
5. Open-Video-Downloader-2.5.2.AppImage does not start. 

**Expected behavior**
I would expect Open-Video-Downloader-2.5.2.AppImage to run on Kubuntu 22.04.3, just like Open-Video-Downloader-2.4.10.AppImage does.

**Additional info (please complete the following information):**
 - OS: Kubuntu 22.04.3
 - Application version: Open-Video-Downloader-2.5.2.AppImage
 - Application type: AppImage

**Comment by StefanLobbenmeier** [comment]
Oh weird. Can you also try version 2.5.0?

**Comment by StefanLobbenmeier** [comment]
https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.5.0

**Comment by Aiden-Shannon** [comment]
Exactly the same issue with 2.5.2 for Pop!_OS 22.04. 
Also tried version 2.5.0 same issue.
2.4.10 Works perfectly.

**Comment by StefanLobbenmeier** [comment]
I see, thanks for testing. Then this is probably related to the Wayland detection. 

Maybe @Cl00e9ment can help debug this? 


for now can you try to find out if you are using Wayland? https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used

**Comment by SnowballV** [comment]
As Aiden-Shannon -
Same issue with Open-Video-Downloader-2.5.0.AppImage as with Open-Video-Downloader-2.5.2.AppImage.
It does not run, on Kubuntu 22.04.3.

And I am not using Wayland, but X11.

Also, I took a look at Kubuntu/Plasma System Monitor.
Even though Open-Video-Downloader-2.5.0.AppImage and Open-Video-Downloader-2.5.2.AppImage won't open, several related processes stay in memory:

For 2.5.0.AppImage:
3 instances of open-video-down
Open-Video-Downloader-2.5.0.AppImage
open-video-downloader.bin--no-sandbox--ozone-platform-hint=auto
open-video-downloader.bin--type=zygote--no-sandbox
open-video-downloader.bin--type=zygote--no-zygote-sandbox--no-sandbox

2.5.2.AppImage:
3 instances of open-video-down
Open-Video-Downloader-2.5.2.AppImage
open-video-downloader.bin--no-sandbox--ozone-platform-hint=auto
open-video-downloader.bin--type=zygote--no-sandbox
open-video-downloader.bin--type=zygote--no-zygote-sandbox--no-sandbox

Perhaps even more processes, but nothing that is clearly relatable to Open Video Downloader, for me.
I will reboot, to make sure memory is cleared.

**Comment by Cl00e9ment** [comment]
It's probably an issue related to the Electron version bump. I don't see how the Wayland detection could be related. I'll test that later this day.

**Comment by Cl00e9ment** [comment]
Can reproduce on my environment (GNOME + Wayland). Running via `npm run start` works fine, but running the built AppImage doesn't.

The culprit is `mkdirp`. Downgrading it to the old  version `1.0.4` fixes the issue. I'll see if there is a clean way to fix that and will make a PR.

**Comment by Cl00e9ment** [comment]
Seems like an issue with mkdirp. I downgraded it to a not so old version (see #75).

**Comment by StefanLobbenmeier** [comment]
Should built into this release: https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.5.3

Hoping that works - on mobile right now

**Comment by StefanLobbenmeier** [comment]
Looks like that didn’t work - will try again tonight

**Comment by StefanLobbenmeier** [comment]
Just ran the release again, that worked. @SnowballV can you confirm that fixes it for you? I do not have a Linux machine to test yet.

**Comment by SnowballV** [comment]
@StefanLobbenmeier,
Yes, I can confirm that fixes the reported issue.
Open-Video-Downloader-2.5.3.AppImage opens as expected, and after closing the before mentioned processes do not stay in memory.
However, one small glitch occurs when opening Open-Video-Downloader-2.5.3.AppImage: most times that I try, there are diagonal lines to be seen for part of a second. I don't see that when opening Open-Video-Downloader-2.4.10.AppImage.

**Comment by Cl00e9ment** [comment]
> However, one small glitch occurs when opening Open-Video-Downloader-2.5.3.AppImage: most times that I try, there are diagonal lines to be seen for part of a second.

Probably because it's now running natively under Wayland (Wayland support is still experimental in Chromium). The problem is that when running with the compatibility layer XWayland, the UI is blurry with fractional scaling. There isn't a perfect solution. If the glitch happen only for less than a second, it's not a big deal I guess.

**Comment by SnowballV** [comment]
> If the glitch happen only for less than a second, it's not a big deal I guess.

Indeed, it's not a big deal.
But I thought it was better to report it, in case it was a symptom of something you needed to know of.
Good that the AppImage now runs as expected. Thanks very much.

**Comment by Cl00e9ment** [comment]
> But I thought it was better to report it

Yes! Thank you, I was indeed not aware of this bug.
