### ISSUE TITLE
Does this software support BiliBili?

### ISSUE THREAD

**Issue by SZ1479** [StefanLobbenmeier/youtube-dl-gui#96]
Hello.

Can Open Video Downloader support the website BiliBili? I get unhandled errors whenever I try to do so:

![Screenshot 2023-12-19 115933](https://github.com/StefanLobbenmeier/youtube-dl-gui/assets/154359024/c75751f0-59c2-4dbd-b6b8-2f8604a4b652)

Thank you in advance.

**Comment by StefanLobbenmeier** [comment]
Supposedly it is supported, there are closed issues for it: https://github.com/yt-dlp/yt-dlp/issues?q=Billibilli

**Comment by StefanLobbenmeier** [comment]
Can you share the full url you were trying to download? Then I can try to reproduce
